[package]
name = "fortune"
version = "0.1.0"
authors = ["Claudio Matsuoka <cmatsuoka@gmail.com>"]

[dependencies]
getopts = "0.2"
byteorder = "1"
regex = "0.2"
rand = "0.3"
rot13 = "0.1"

[profile.release]
lto = true
